import Head from 'next/head';
import { useWeb3 } from "@3rdweb/hooks"
import Dashboard from './Dashboard';
import Login from '../components/Login';

export default function Home() {
  const { address } = useWeb3()
  return (
    <div className="bg-[#0a0b0d]">
      <Head>
        <title>Coinbase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {address ? (<Dashboard address={address}/>) : (
     <Login/>
    )
    }
    
    </div>
  )
}

